"""phase 18a structured patch fields

Revision ID: 278a4959d4c5
Revises: 9c94c8ca7e64
Create Date: 2026-05-19 07:01:41.369679+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '278a4959d4c5'
down_revision: str | None = '9c94c8ca7e64'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_explanations', sa.Column('patch_kind', sa.Text(), nullable=True))
    op.add_column('ai_explanations', sa.Column('patch_target', sa.Text(), nullable=True))
    op.add_column('ai_explanations', sa.Column('patch_summary', sa.Text(), nullable=True))
    op.add_column('ai_explanations', sa.Column('patch_confidence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_explanations', 'patch_confidence')
    op.drop_column('ai_explanations', 'patch_summary')
    op.drop_column('ai_explanations', 'patch_target')
    op.drop_column('ai_explanations', 'patch_kind')
    # ### end Alembic commands ###
