"""phase 16 terms acceptance fields

Revision ID: 9c94c8ca7e64
Revises: f0bea223e886
Create Date: 2026-05-18 17:47:17.757824+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '9c94c8ca7e64'
down_revision: str | None = 'f0bea223e886'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_version_accepted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_ip', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted_ip')
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_version_accepted')
    # ### end Alembic commands ###
