"""add processed_polar_events

Revision ID: 43104b8e5d92
Revises: 2d8cce1f09b0
Create Date: 2026-05-16 17:58:29.834728+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '43104b8e5d92'
down_revision: str | None = '2d8cce1f09b0'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_polar_events',
    sa.Column('polar_event_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('polar_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_polar_events')
    # ### end Alembic commands ###
