"""phase 13 slack installations

Revision ID: 76fc65026c43
Revises: 43104b8e5d92
Create Date: 2026-05-18 08:53:10.085400+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '76fc65026c43'
down_revision: str | None = '43104b8e5d92'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('bot_user_id', sa.Text(), nullable=False),
    sa.Column('bot_token_encrypted', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('authed_user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.add_column('notification_deliveries', sa.Column('external_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_deliveries', 'external_id')
    op.drop_table('slack_installations')
    # ### end Alembic commands ###
