"""phase 14 public status pages

Revision ID: f0bea223e886
Revises: 76fc65026c43
Create Date: 2026-05-18 12:51:12.609183+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'f0bea223e886'
down_revision: str | None = '76fc65026c43'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('organizations', sa.Column('status_page_slug', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('status_page_headline', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['status_page_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'status_page_headline')
    op.drop_column('organizations', 'status_page_slug')
    op.drop_column('monitors', 'is_public')
    # ### end Alembic commands ###
